[project]
name = "un80-statements"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.5",
    "ipykernel>=7.1.0",
    "libsql-experimental>=0.0.55",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
]
